// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.Upload
{
    using System;
    using System.Web;

    internal class AsyncProgressWorkerRequest : ProgressWorkerRequest
    {
        public AsyncProgressWorkerRequest(HttpWorkerRequest wr, HttpRequest request)
            : base(wr, request)
        {
        }

        protected override void UpdateProgress(byte[] buffer, int validBytes)
        {
            base.RequestStateStore.UpdateCurrentRequestBytesCount(validBytes);
        }
    }
}
