// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    using System;

    public class AsyncUploadHandlerExeption : Exception
    {
        public AsyncUploadHandlerExeption(string msg)
            : base(msg)
        {
        }
    }
}
