// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    internal class CryptoService
    {
        public static string Decrypt(string encryptedString)
        {
            return (string)LosSerializer.Deserialize(encryptedString, true);
        }

        public static string Encrypt(string plainString)
        {
            return LosSerializer.Serialize(plainString, true);
        }
    }
}
