// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    using System;
    using System.Collections.Specialized;
    using Areas.Lib.UploadProgress;

    public interface IRequestData
    {
        NameValueCollection FormValues { get; set; }

        Areas.Lib.UploadProgress.UploadedFile UploadedFile { get; set; }
    }
}
