// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    public class MetaData
    {
        public string AsyncUploadTypeName { get; set; }

        public string TempFileName { get; set; }
    }
}
