// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    using System;
    using Areas.Lib.UploadProgress;
    using Areas.Lib.UploadProgress.Upload;

    internal class RadAsyncUploadContext : RadUploadContext
    {
        private int uploadsInProgress;
        private readonly object uploadsLock;

        internal RadAsyncUploadContext(int requestLength, RequestStateStore stateStore)
            : base(requestLength, stateStore)
        {
            this.uploadsLock = new object();
        }

        public int UploadsInProgress
        {
            get
            {
                lock (this.uploadsLock)
                {
                    return this.uploadsInProgress;
                }
            }
            set
            {
                lock (this.uploadsLock)
                {
                    this.uploadsInProgress = value;
                }
            }
        }
    }
}
