// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll

using System;
using System.Collections.Specialized;
using System.Web;

namespace Areas.Lib.UploadProgress.AsyncUpload
{
    internal class RequestData : IRequestData
    {
        public RequestData()
        {
        }

        public RequestData(HttpContext context)
        {
            this.FormValues = context.Request.Form;
            try
            {
                this.UploadedFile = Areas.Lib.UploadProgress.UploadedFile.FromHttpPostedFile(context.Request.Files[0]);
            }
            catch (ArgumentOutOfRangeException)
            {
                throw new AsyncUploadHandlerExeption("RadAsyncUpload handler is registered succesfully, however, it may not be accessed directly.");
            }
        }

        public NameValueCollection FormValues { get; set; }

        public Areas.Lib.UploadProgress.UploadedFile UploadedFile { get; set; }
    }
}
