// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll

using System.Web;

namespace Areas.Lib.UploadProgress.AsyncUpload
{
    internal class ResponseWriter : IResponseWriter
    {
        public ResponseWriter()
        {
        }

        public ResponseWriter(HttpContext context)
        {
            this.Context = context;
        }

        public void WriteToResponse(string response)
        {
            this.Context.Response.ContentType = "text/html";
            this.Context.Response.Write(response);
        }

        public HttpContext Context { get; set; }
    }
}
