// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress.AsyncUpload
{
    using System;
    using System.IO;

    public static class StreamExtensions
    {
        private const int BufferSize = 0x1000;

        public static void CopyTo(Stream source, Stream dest)
        {
            int num;
            byte[] buffer = new byte[0x1000];
            while ((num = source.Read(buffer, 0, buffer.Length)) != 0)
            {
                dest.Write(buffer, 0, num);
            }
        }
    }
}
