// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress
{
    using System;
    using System.Runtime.CompilerServices;

    [Serializable]
    public class AsyncUploadConfiguration : IAsyncUploadConfiguration
    {
        public AsyncUploadConfiguration()
        {
        }

        public AsyncUploadConfiguration(string targetFolder, string tempTargetFolder, int maxFileSize, TimeSpan timeToLive)
        {
            this.TargetFolder = targetFolder;
            this.TempTargetFolder = tempTargetFolder;
            this.MaxFileSize = maxFileSize;
            this.TimeToLive = timeToLive;
        }

        public int MaxFileSize { get; set; }

        public string TargetFolder { get; set; }

        public string TempTargetFolder { get; set; }

        public TimeSpan TimeToLive { get; set; }
    }
}
