// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress
{
    using System;

    public enum CompressionType
    {
        None,
        GZip,
        Deflate
    }
}
