// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress
{
    using System;

    public interface IAsyncUploadResult
    {
        int ContentLength { get; set; }

        string ContentType { get; set; }

        string FileName { get; set; }
    }
}
