// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress
{
    using System;

    public interface IAsyncUploadConfiguration
    {
        int MaxFileSize { get; set; }

        string TargetFolder { get; set; }

        string TempTargetFolder { get; set; }

        TimeSpan TimeToLive { get; set; }
    }
}
