// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll

using System.IO;
using System.Web.UI;

namespace Areas.Lib.UploadProgress
{
    public static class LosSerializer
    {
        public static object Deserialize(string serializedObject)
        {
            return Deserialize(serializedObject, false);
        }

        public static object Deserialize(string serializedObject, bool enableMacValidation)
        {
            LosFormatter formatter = enableMacValidation ? new LosFormatter(true, "string") : new LosFormatter();
            return formatter.Deserialize(serializedObject);
        }

        public static string Serialize(object objectToSerialize)
        {
            return Serialize(objectToSerialize, false);
        }

        public static string Serialize(object objectToSerialize, bool enableMacValidation)
        {
            LosFormatter formatter = enableMacValidation ? new LosFormatter(true, "string") : new LosFormatter();
            StringWriter output = new StringWriter();
            formatter.Serialize(output, objectToSerialize);
            return output.ToString();
        }
    }
}
