// Generated by Reflector from D:\eConsular\src\Areas\Lib\RadWebUI\Areas.Lib.UploadProgress.dll
namespace Areas.Lib.UploadProgress
{
    using System;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class UploadedFileInfo : IAsyncUploadResult
    {
        public UploadedFileInfo()
        {
        }

        public UploadedFileInfo(UploadedFile file)
        {
            CopyFileInfo(this, file);
        }

        public static void CopyFileInfo(IAsyncUploadResult result, UploadedFile file)
        {
            result.ContentLength = file.ContentLength;
            result.ContentType = file.ContentType;
            result.FileName = Path.GetFileName(file.FileName);
        }

        public int ContentLength { get; set; }

        public string ContentType { get; set; }

        public string FileName { get; set; }

        internal string FileType { get; set; }

        public int Index { get; set; }

        internal string SerializedData { get; set; }

        internal string TempFileName { get; set; }
    }
}
